version: '3.7'
services:
  weirdtext:
    build:
      context: weirdtext/
    restart: always
    container_name: weirdtext
    ports:
      - 8000:8000
  nginx:
    build: ./nginx
    restart: always
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - weirdtext